eureka:
  client:
    fetchRegistry: true
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true
    hostname: localhost
server:
  port: 9094
spring:
  application:
    name: gateway-server
  zipkin:
    base-url: http://localhost:9411/
  sleuth:
    sampler:
      probability: 1
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lowerCaseServiceId: true
